# vim: set ft=ruby :

$provision_script = <<HERE
#!/bin/bash

apt-get update

apt-get -y install git vim byobu \
g++ make libtool autoconf automake pkg-config \
libssl-dev tcl-dev libexpat1-dev libpcre3-dev libmodule-install-perl \
bison flex

echo "set -o vi" > /etc/profile.d/custom.sh
echo "export EDITOR=$(which vim)" >> /etc/profile.d/custom.sh
HERE

Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.provision "shell", inline: $provision_script

    if Vagrant.has_plugin?("landrush")
	config.landrush.enable
	config.vm.hostname = "ts.vagrant.dev"
	config.vm.network "private_network", ip: "192.168.22.4"
    end

    if Vagrant.has_plugin?("vagrant-cachier")
	config.cache.auto_detect = true
    end
end

